import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import Navbar from "@/components/navbar/navbar"
import { ThemeProvider } from "next-themes"
import { TooltipProvider } from "@/components/ui/tooltip"
import { Toaster } from "@/components/ui/sonner"
import { getServerSession } from "@/lib/auth-server"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
})

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
})

export const metadata: Metadata = {
    title: "Pokémoves",
    description: "Generated by create next app",
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    const session = await getServerSession()

    return (
        <html
            lang="en"
            className={ `${geistSans.variable} ${geistMono.variable} h-full antialiased` }
            suppressHydrationWarning
        >
            <body className="min-h-full flex flex-col">
                <TooltipProvider delayDuration={ 500 }>
                    <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                        <Navbar
                            // Pass the initial user to the Navbar component
                            initialUser={
                                session?.user
                                    ? {
                                        name: session.user.name ?? null,
                                        username: session.user.username ?? null,
                                    }
                                    : null
                            }
                        />
                        { children }
                        <Toaster />
                    </ThemeProvider>
                </TooltipProvider>
            </body>
        </html>
    )
}
